default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: lista_de_compras_development

test:
  <<: *default
  database: lista_de_compras_test

production:
  <<: *default
  database: lista_de_compras_production
  username: lista_de_compras
  password: <%= ENV["LISTA_DE_COMPRAS_DATABASE_PASSWORD"] %>
